apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow-kserve
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    appSource: aws
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/awslabs/kubeflow-manifests.git
    targetRevision: main
    path: awsconfigs/apps/kserve
    helm:
  syncPolicy:
    automated:
      prune: true