apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow-namespace
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    appSource: upstream
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/kubeflow/manifests.git
    targetRevision: master
    path: common/kubeflow-namespace/base
  syncPolicy:
    automated:
      prune: true