resources:
- istio.yaml
- dex.yaml
- oidc-authservice.yaml
- cluster-local-gateway.yaml
- kubeflow-namespace.yaml
- istio-resources.yaml
- kubeflow-roles.yaml
- kubeflow-issuer.yaml
- knative-serving.yaml
- knative-eventing.yaml
- kserve.yaml