apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow-notebook-controller
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    appSource: inline
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/arunvthangaraj/aws-observability-accelerator.git
    targetRevision: main
    path: artifacts/argocd-apps/teams/team-yoda/prod/notebook-controller
  syncPolicy:
    automated:
      prune: true