apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow-pipeline
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    appSource: upstream
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/kubeflow/manifests.git
    targetRevision: master
    path: apps/pipeline/upstream/env/cert-manager/platform-agnostic-multi-user
  syncPolicy:
    automated:
      prune: true