apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubeflow-git
  namespace: default
spec:
  interval: 5m
  url: https://github.com/kubeflow/manifests.git
  ref:
    branch: master
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubeflow-Kustomization
  namespace: default
spec:
  interval: 10m
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: kubeflow-git
  path: "./common/kubeflow-namespace/base"
  prune: true
  timeout: 1m